//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Managemant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books1
    {
        public int BookID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PublishedYear { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> PublisherID { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
